# Generated by Django 4.0.4 on 2022-05-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Join_date',
            new_name='DOB',
        ),
    ]
