# Generated by Django 4.0.4 on 2022-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
